# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lecture_hall', models.CharField(max_length=50, verbose_name='Аудитория')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAdditionalMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_material', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLiterature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('full_mark', models.IntegerField(default=100)),
                ('simple_mark', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('euro_mark', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('na_status', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectOfUnivGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('closing_date', models.DateField(default=django.utils.timezone.now)),
                ('hours_count', models.IntegerField(default=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')])),
                ('lesson_num', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('lecture_hall', models.CharField(max_length=50, null=True, verbose_name='Аудитория')),
                ('subject_denominator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='знаменатель', to='subject_controller.SubjectOfUnivGroup')),
                ('subject_numerator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='числитель', to='subject_controller.SubjectOfUnivGroup')),
                ('univ_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup'),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher'),
        ),
        migrations.AddField(
            model_name='groupexam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup'),
        ),
        migrations.AddField(
            model_name='groupexam',
            name='univ_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='weekschedule',
            unique_together=set([('day', 'lesson_num', 'univ_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='subjectofunivgroup',
            unique_together=set([('group', 'subject')]),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmark',
            unique_together=set([('student', 'subject')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupexam',
            unique_together=set([('subject', 'univ_group')]),
        ),
    ]
