# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20180322_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Friday', 'Friday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], default='Monday', max_length=15)),
                ('lecture_hall', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('teacer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAdditionalMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLiterature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectOfUnivGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject_controller.Subject'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='univ_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup'),
        ),
    ]
