# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekschedule',
            old_name='lecture_hall',
            new_name='lecture_hall_denominator',
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='lecture_hall_numerator',
            field=models.CharField(max_length=50, null=True, verbose_name='Аудитория'),
        ),
    ]
