# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0002_subjectmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='teacer',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='simple_mark',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=5),
        ),
    ]
