# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0002_auto_20180603_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekschedule',
            name='lecture_hall_denominator',
            field=models.CharField(max_length=50, null=True, verbose_name='Аудитория знам'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='lecture_hall_numerator',
            field=models.CharField(max_length=50, null=True, verbose_name='Аудитория чис'),
        ),
    ]
