# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0003_auto_20180508_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 8, 21, 25, 26, 946834, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='subjectmark',
            name='full_mark',
            field=models.IntegerField(default=100),
        ),
    ]
