# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0004_auto_20180508_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup'),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 8, 21, 46, 17, 864600, tzinfo=utc)),
        ),
    ]
