# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0004_auto_20180604_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Sunday', 'Суббота')], default='Monday', max_length=20),
        ),
    ]
