# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0005_auto_20180604_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectofunivgroup',
            options={'ordering': ['semester']},
        ),
    ]
