# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0006_auto_20180605_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlab',
            name='name',
            field=models.CharField(default='Лабораторная работа', max_length=256),
        ),
        migrations.AddField(
            model_name='subjectlecture',
            name='name',
            field=models.CharField(default='Лекция', max_length=256),
        ),
    ]
