# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0007_auto_20180508_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexam',
            name='exam_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
