# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0008_auto_20180606_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectliterature',
            name='literature_url',
        ),
        migrations.AddField(
            model_name='subjectliterature',
            name='literature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
