# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180509_1305'),
        ('subject_controller', '0008_auto_20180508_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectadditionalmaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='subjectlab',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='subjectlecture',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='subjectliterature',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='subject_denominator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='знаменатель', to='subject_controller.SubjectOfUnivGroup'),
        ),
        migrations.AlterField(
            model_name='groupexam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='subject_numerator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='числитель', to='subject_controller.SubjectOfUnivGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupexam',
            unique_together=set([('subject', 'univ_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmark',
            unique_together=set([('student', 'subject')]),
        ),
        migrations.AlterUniqueTogether(
            name='subjectofunivgroup',
            unique_together=set([('group', 'subject')]),
        ),
        migrations.RemoveField(
            model_name='weekschedule',
            name='subject_denumerator',
        ),
        migrations.AlterUniqueTogether(
            name='weekschedule',
            unique_together=set([('day', 'lesson_num', 'univ_group')]),
        ),
    ]
