# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0009_auto_20180509_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectofunivgroup',
            name='closing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subjectofunivgroup',
            name='hours_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subjectofunivgroup',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=1),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='na_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='simple_mark',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
