# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 09:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180605_1318'),
        ('subject_controller', '0010_auto_20180606_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('full_mark', models.IntegerField(default=100)),
                ('simple_mark', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('euro_mark', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup')),
                ('univ_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='full_mark',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
