# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0010_auto_20180509_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='euro_mark',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
        ),
    ]
