# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0012_auto_20180529_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekschedule',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='lesson_num',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
        ),
    ]
