# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0012_auto_20180608_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsubjectmark',
            options={'verbose_name': 'Оценка по экзамену', 'verbose_name_plural': 'Список оценок по экзаменам'},
        ),
        migrations.AlterModelOptions(
            name='groupexam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Список экзаменов'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предметы', 'verbose_name_plural': 'Предмет'},
        ),
        migrations.AlterModelOptions(
            name='subjectadditionalmaterial',
            options={'verbose_name': 'Дополнительные материалы', 'verbose_name_plural': 'Дополнительные материалы'},
        ),
        migrations.AlterModelOptions(
            name='subjectlab',
            options={'ordering': ['pk'], 'verbose_name': 'Лабораторная работа', 'verbose_name_plural': 'Список лабораторных работ'},
        ),
        migrations.AlterModelOptions(
            name='subjectlecture',
            options={'ordering': ['pk'], 'verbose_name': 'Лекция', 'verbose_name_plural': 'Список лекций'},
        ),
        migrations.AlterModelOptions(
            name='subjectliterature',
            options={'verbose_name': 'Литература предмета', 'verbose_name_plural': 'Литература предмета'},
        ),
        migrations.AlterModelOptions(
            name='subjectofunivgroup',
            options={'ordering': ['semester'], 'verbose_name': 'Предмет группы', 'verbose_name_plural': 'Предметы группы'},
        ),
        migrations.AlterModelOptions(
            name='weekschedule',
            options={'ordering': ['day'], 'verbose_name': 'Элемент расписания', 'verbose_name_plural': 'Элементы расписания'},
        ),
    ]
