# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0013_auto_20180608_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsubjectmark',
            options={'verbose_name': 'Оценка по экзамену', 'verbose_name_plural': 'Оценоки по экзаменам'},
        ),
        migrations.AlterModelOptions(
            name='studentsubjectmark',
            options={'verbose_name': 'Оценка по экзамену', 'verbose_name_plural': 'Список оценок по экзаменам'},
        ),
    ]
