# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0015_auto_20180608_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='semester',
            field=models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1.0),
        ),
    ]
