# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180605_1318'),
        ('subject_controller', '0018_auto_20180608_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsubjectmark',
            unique_together=set([('student', 'subject', 'date')]),
        ),
    ]
