# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180605_1318'),
        ('subject_controller', '0019_auto_20180608_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectmark',
            name='semester',
            field=models.FloatField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], default=1.0),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectmark',
            unique_together=set([('student', 'subject', 'semester')]),
        ),
    ]
