# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0020_auto_20180608_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectliterature',
            name='literature',
            field=models.TextField(blank=True, null=True, verbose_name='Литература'),
        ),
    ]
