# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0022_auto_20180608_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectliterature',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Предмет', to='subject_controller.Subject'),
        ),
    ]
