# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0023_auto_20180608_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='subjectliterature',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject', verbose_name='Предмет'),
        ),
    ]
