# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 13:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0024_auto_20180608_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubjectmark',
            name='na_status',
        ),
        migrations.AlterField(
            model_name='examsubjectmark',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='examsubjectmark',
            name='euro_mark',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1, verbose_name='EU оценка'),
        ),
        migrations.AlterField(
            model_name='examsubjectmark',
            name='full_mark',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='examsubjectmark',
            name='simple_mark',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Упрощенная оценка'),
        ),
        migrations.AlterField(
            model_name='examsubjectmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='examsubjectmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='examsubjectmark',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='groupexam',
            name='exam_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='groupexam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='groupexam',
            name='univ_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='euro_mark',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1, verbose_name='EU оценка'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='full_mark',
            field=models.IntegerField(default=100, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='semester',
            field=models.FloatField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], default=1.0, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='simple_mark',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Упрощенная оценка'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.SubjectOfUnivGroup', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='univ_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subjectadditionalmaterial',
            name='additional_material',
            field=models.TextField(blank=True, null=True, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='subjectadditionalmaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectlab',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectlecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='closing_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='hours_count',
            field=models.IntegerField(default=100, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='semester_quantity',
            field=models.FloatField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], default=1.0, verbose_name='Количество семестров'),
        ),
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='start_semester',
            field=models.FloatField(choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0)], default=1.0, verbose_name='Начальный семестр'),
        ),
        migrations.AlterField(
            model_name='subjectofunivgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_controller.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Sunday', 'Суббота')], default='Monday', max_length=20, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='lesson_num',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, verbose_name='Номер ленты'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='univ_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup', verbose_name='Группа'),
        ),
    ]
