# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180605_1318'),
        ('subject_controller', '0028_remove_studentsubjectmark_univ_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Текст')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Преподаватель')),
                ('univ_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnivGroup', verbose_name='Группа')),
            ],
        ),
    ]
