# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teacher_about'),
        ('subject_controller', '0033_examsubjectmark_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsubjectmark',
            unique_together=set([('student', 'subject', 'semester')]),
        ),
    ]
