# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0034_auto_20180621_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
    ]
