# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 18:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0037_auto_20180622_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectmark',
            name='full_mark',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Оценка'),
        ),
    ]
