# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0038_auto_20180622_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weekschedule',
            unique_together=set([('day', 'lesson_num', 'subject_numerator', 'subject_denominator')]),
        ),
    ]
