# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_controller', '0039_auto_20180622_2146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weekschedule',
            unique_together=set([('day', 'lesson_num')]),
        ),
    ]
