# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-24 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180623_2124'),
        ('subject_controller', '0040_auto_20180623_2309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupexam',
            unique_together=set([('subject', 'univ_group', 'exam_datetime')]),
        ),
    ]
