# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacer',
        ),
        migrations.AddField(
            model_name='student',
            name='univ_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.UnivGroup'),
        ),
        migrations.AddField(
            model_name='univgroup',
            name='group_name',
            field=models.CharField(default='as', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
