# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['univ_group']},
        ),
        migrations.AlterModelOptions(
            name='univgroup',
            options={'ordering': ['group_name']},
        ),
    ]
