# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180509_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='univgroup',
            name='enter_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='univgroup',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
