# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='FIO',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='test', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='test', max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='test', max_length=150, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='test', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='test', max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(default='test', max_length=150, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
