# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180605_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_media', verbose_name='Фото'),
        ),
    ]
