# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180610_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
