# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teacher_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
