# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180622_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_number',
            field=models.CharField(max_length=10),
        ),
    ]
