# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180622_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=256, verbose_name='Должность'),
        ),
    ]
