# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180623_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='other_position',
            field=models.TextField(verbose_name='Другие должности'),
        ),
    ]
