# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180623_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.CharField(max_length=10, verbose_name='Кабинет'),
        ),
    ]
