# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180623_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='about',
        ),
    ]
