# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_teacher_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_rank',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='other_position',
            field=models.TextField(blank=True, null=True, verbose_name='Другие должности'),
        ),
    ]
